// Generate the QR matrix for the sticker as a static TS module (no runtime dep
// in the Remotion bundle). Re-run whenever the target URL changes:
//   node scripts/generate-qr.mjs "https://ta-vraie-url.app"
import QRCode from "qrcode";
import { writeFile } from "node:fs/promises";

const target = process.argv[2] || "https://meyebus.app";
// High error correction (H) so a centered logo can cover ~30% without breaking scans.
const qr = QRCode.create(target, { errorCorrectionLevel: "H" });
const size = qr.modules.size;
const data = Array.from(qr.modules.data); // 1 = dark module

const out = `// AUTO-GENERATED by scripts/generate-qr.mjs — do not edit by hand.
// Target URL encoded in the QR:
export const QR_TARGET = ${JSON.stringify(target)};
export const QR_SIZE = ${size};
export const QR_MODULES: number[] = [${data.join(",")}];
`;
await writeFile(new URL("../src/meyebus/stickers/qr-data.ts", import.meta.url), out);
console.log(`QR généré pour ${target} — matrice ${size}×${size}.`);
